version: '3.1'
services:
  db:
    image: postgres:14.5-alpine
    container_name: library_of_books_DB
    ports:
      - 5080:5432
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: library
      POSTGRES_USER: library
      POSTGRES_DB: library_of_books_DB
    restart: always
volumes:
  psql:
